#!/usr/bin/env bash
#Install load balancer


echo "Updating and installing nginx"
sudo apt-get -y update 
sudo apt-get install -y haproxy

server_config =\
"
  defaults 
     mode http
     timeout client 30s
     timeout connect 10s
     timeout server 15s
     timeout http-request 10s
  frontend tech-frontend *:80
     default_backend biscode
  backend biscode
     balance roundrobin
     server 3137-web-01 3.236.145.18:80 check
     server 3137-web-02 3.236.124.214:80 check
 "

# enable haproxy to start by init script
echo "ENABLED=1" | sudo dd status=none of/etc/default/haproxy

sudo service haproxy start

