#!/usr/bin/env bash
#this script create a pid file
#display 'to infinity and beyond'
#display 'i hate to kill command' at SIGTERM signal
#display 'Y u no love me?!' at SIGINT signal
#delete the pid file and terminate

sudo touch /var/run/myscript.pid

sudo bash -c "echo $$ > /var/run/myscript.pid"

trap interrup2 SIGINT
trap interrup1 SIGTERM
trap interrup3 SIGQUIT

interrup3()
{
    sudo rm /var/run/myscript.pid
    exit $?
}

interrup2()
{
    echo "Y U no love me?!"
}

interrup1()
{
    echo "I hate the kill command"
    sudo rm /var/run/myscript.pid
    exit $?
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
